name: WindBro
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - numpy=1.24.3
  - pandas=1.5.3
  - pathlib=1.0.1
  - pyproj=3.4.1
  - scipy=1.10.1
  - pillow=9.4.0
  - matplotlib=3.7.1
  - requests=2.31.0
  - urllib3=1.26.16
  - ipywidgets=7.6.5
  - ipython=8.15.0
  - cartopy=0.21.1
  - ipympl=0.9.3
  - cython=3.0.0
